### ISSUE TITLE
I’m here to help you with your own bdo 

### ISSUE THREAD

**Issue by jabombingme** [lvps/389ds-server#20]
So how can it be ethnically ok if I’m the owner an the target??? Anyone else think that’s strange? Fuck Wikipedia fuck the reduction an fuck the program manager who has cloned me an taking 50$ a day from my account- an I found out not for months…. An something will happen to be a big player an experience I soon not forget however you are 21 cola berating my life so who is the one who knows what to do now

**Comment by lvps** [comment]
Sure, I did totally understand this, every single word of it.
