### ISSUE TITLE
schema reload doesn't work

### ISSUE THREAD

**Issue by falon** [lvps/389ds-server#25]
https://github.com/lvps/389ds-server/blob/8b151c4e23d3789fc27d168f05bcdc34ffcf2300/tasks/main.yml#L102-L119

Maybe you mean

```
- name: "Reload schema on {{ dirsrv_serverid }}"
  tags: dirsrv_schema
  ldap_entry: [...]
  when: not dirsrv_restart_condition_has_restarted|default(false) and (
      ( dirsrv_restart_condition_schema_reload_1 is defined and dirsrv_restart_condition_schema_reload_1.changed ) or
      ( dirsrv_restart_condition_schema_reload_2 is defined and dirsrv_restart_condition_schema_reload_2.changed )
    )
```

In this way it works very pretty for me.

**Comment by falon** [comment]
Thank you to add this.
I saw at the commit. Did you forget the `tags: dirsrv_schema`?
If I run the role for schema reloading only, if the tag is not present then the schema will never reload.

**Comment by lvps** [comment]
Oops, my bad, I've added the tags now
